import { eventTarget, getEnabledElement, metaData, utilities as coreUtilities } from '@cornerstonejs/core';
import type { Types as CoreTypes } from '@cornerstonejs/core';
import * as cornerstoneTools from '@cornerstonejs/tools';
import {
  calculateNasalSeptumDeviation,
  calculateNasalSeptumDeviationInWorld,
  isValidPixelSpacing,
  NASAL_SEPTUM_DEVIATION_COLOR,
  NASAL_SEPTUM_DEVIATION_TOOL_NAME,
} from '../services/nasalSeptumDeviation';

type InteractionEvent = cornerstoneTools.Types.EventTypes.InteractionEventType;
type Annotation = cornerstoneTools.Types.Annotation;
type ToolHandle = cornerstoneTools.Types.ToolHandle;
type SvgDrawingHelper = cornerstoneTools.Types.SVGDrawingHelper;

interface NasalSeptumToolData {
  step: number;
  axisLengthMm?: number;
  deviationLengthMm?: number;
  pixelSpacing?: [number, number];
  error?: string;
}

interface EditData {
  annotation: Annotation;
  element: HTMLDivElement;
  handleIndex?: number;
  lastWorld?: CoreTypes.Point3;
}

function dispatchAnnotationEvent(eventName: string, annotation: Annotation, element: HTMLDivElement): void {
  eventTarget.dispatchEvent(new CustomEvent(eventName, {
    detail: { annotation, element },
  }));
}

function pointDistanceToSegment(point: CoreTypes.Point2, start: CoreTypes.Point2, end: CoreTypes.Point2): number {
  const dx = end[0] - start[0];
  const dy = end[1] - start[1];
  const lengthSquared = dx * dx + dy * dy;
  if (lengthSquared === 0) return Math.hypot(point[0] - start[0], point[1] - start[1]);

  const factor = Math.max(0, Math.min(1,
    ((point[0] - start[0]) * dx + (point[1] - start[1]) * dy) / lengthSquared
  ));
  return Math.hypot(
    point[0] - (start[0] + factor * dx),
    point[1] - (start[1] + factor * dy)
  );
}

function validWorldPoint(point: unknown): point is CoreTypes.Point3 {
  const values = Array.isArray(point)
    ? point
    : ArrayBuffer.isView(point)
      ? Array.from(point as unknown as ArrayLike<number>)
      : null;
  return Boolean(values && values.length >= 3 && values.slice(0, 3).every(value => Number.isFinite(value)));
}

export default class NasalSeptumDeviationTool extends cornerstoneTools.AnnotationTool {
  static toolName = NASAL_SEPTUM_DEVIATION_TOOL_NAME;

  private creation: { annotation: Annotation; element: HTMLDivElement } | null = null;
  private nasalEditData: EditData | null = null;
  private renderLogState = new Map<string, string>();

  private debug(event: string, details?: unknown): void {
    console.info(`[NasalSeptumDeviationTool] ${event}`, details ?? '');
  }

  constructor(
    toolProps: cornerstoneTools.Types.PublicToolProps = {},
    defaultToolProps: cornerstoneTools.Types.ToolProps = {
      supportedInteractionTypes: ['Mouse'],
      configuration: {
        preventHandleOutsideImage: false,
      },
    }
  ) {
    super(toolProps, defaultToolProps);
  }

  addNewAnnotation = (evt: InteractionEvent): Annotation => {
    const { currentPoints, element } = evt.detail;
    const worldPoint = [...currentPoints.world] as CoreTypes.Point3;
    this.debug('addNewAnnotation / primer click', {
      worldPoint,
      nativeButton: (evt.detail.event as MouseEvent | undefined)?.button,
      nativeButtons: (evt.detail.event as MouseEvent | undefined)?.buttons,
      element: element?.className,
    });
    const enabledElement = getEnabledElement(element);
    const { viewport } = enabledElement;
    const camera = viewport.getCamera();
    const referencedImageId = this.getReferencedImageId(
      viewport,
      worldPoint,
      camera.viewPlaneNormal,
      camera.viewUp
    );

    const annotation = {
      annotationUID: coreUtilities.uuidv4(),
      highlighted: true,
      invalidated: true,
      autoGenerated: false,
      isLocked: false,
      isVisible: true,
      metadata: {
        ...viewport.getViewReference({ points: [worldPoint] }),
        toolName: this.getToolName(),
        referencedImageId,
        FrameOfReferenceUID: viewport.getFrameOfReferenceUID(),
      },
      data: {
        handles: {
          points: [worldPoint],
          activeHandleIndex: null,
          textBox: {
            hasMoved: false,
            worldPosition: [...worldPoint],
            worldBoundingBox: {
              topLeft: [...worldPoint],
              topRight: [...worldPoint],
              bottomLeft: [...worldPoint],
              bottomRight: [...worldPoint],
            },
          },
        },
        cachedStats: {},
        nasalSeptumDeviation: {
          step: 1,
        } satisfies NasalSeptumToolData,
      },
    } as unknown as Annotation;

    cornerstoneTools.annotation.state.addAnnotation(annotation, element);
    this.creation = { annotation, element };
    cornerstoneTools.state.isInteractingWithTool = true;
    this.debug('creación iniciada', {
      annotationUID: annotation.annotationUID,
      step: 1,
      points: annotation.data.handles.points,
      referencedImageId,
    });
    element.addEventListener(
      cornerstoneTools.Enums.Events.MOUSE_DOWN,
      this.handleCreationMouseDown as EventListener
    );

    evt.preventDefault();
    viewport.render();
    return annotation;
  };

  private handleCreationMouseDown = (rawEvent: Event): void => {
    const evt = rawEvent as unknown as InteractionEvent;
    const creation = this.creation;
    if (!creation) return;

    const { annotation, element } = creation;
    const eventDetail = evt.detail;
    const nativeEvent = eventDetail?.event as { button?: number; preventDefault?: () => void } | undefined;
    this.debug('MOUSE_DOWN durante creación', {
      step: (annotation.data.nasalSeptumDeviation as NasalSeptumToolData).step,
      button: nativeEvent?.button,
      buttons: (eventDetail?.event as MouseEvent | undefined)?.buttons,
      worldPoint: eventDetail?.currentPoints?.world,
    });
    if (!eventDetail?.currentPoints?.world ||
        (nativeEvent?.button !== undefined && nativeEvent.button !== 0)) return;

    // This tool is click-driven: mouse movement must never mutate its points.
    evt.preventDefault();

    const worldPoint = [...eventDetail.currentPoints.world] as CoreTypes.Point3;
    const points = annotation.data.handles.points as CoreTypes.Point3[];
    const data = annotation.data.nasalSeptumDeviation as NasalSeptumToolData;

    if (data.step === 1) {
      points.push(worldPoint);
      data.step = 2;
      this.debug('segundo click aceptado / axis_end', { points: [...points], step: data.step });
      nativeEvent?.preventDefault?.();
      getEnabledElement(element).viewport.render();
      return;
    }

    if (data.step !== 2) return;

    points.push(worldPoint);
    data.step = 3;
    this.debug('tercer click aceptado / deviation_point', { points: [...points], step: data.step });
    this.completeAnnotation(annotation, element);
    nativeEvent?.preventDefault?.();
  };

  private completeAnnotation(annotation: Annotation, element: HTMLDivElement): void {
    const enabledElement = getEnabledElement(element);
    const { viewport } = enabledElement;
    const points = annotation.data.handles.points as CoreTypes.Point3[];
    const data = annotation.data.nasalSeptumDeviation as NasalSeptumToolData;
    const imageData: any = viewport.getImageData()?.imageData || viewport.getImageData();
    const referencedImageId = annotation.metadata.referencedImageId;
    const isVolumeViewport = this.isVolumeViewport(viewport);
    this.debug('completando medición', {
      annotationUID: annotation.annotationUID,
      pointsBeforeProjection: [...points],
      referencedImageId,
      isVolumeViewport,
      imageDataAvailable: Boolean(imageData),
      hasWorldToIndex: Boolean(imageData?.worldToIndex),
      hasIndexToWorld: Boolean(imageData?.indexToWorld),
    });

    if (!imageData?.worldToIndex || !imageData.indexToWorld || (!isVolumeViewport && !referencedImageId)) {
      data.error = 'No se pudo obtener la transformación de la imagen DICOM';
      console.warn('[NasalSeptumDeviationTool] transformación DICOM no disponible', { imageData, referencedImageId });
      this.finishCreation(annotation, element);
      return;
    }

    const pixelSpacing = isVolumeViewport
      ? this.getVolumePixelSpacing(imageData)
      : this.getPixelSpacing(referencedImageId, imageData);
    if (!isValidPixelSpacing(pixelSpacing)) {
      data.error = 'La imagen no tiene Pixel Spacing válido para calcular milímetros';
      console.warn('[NasalSeptumDeviationTool] Pixel Spacing inválido', { pixelSpacing, referencedImageId });
      this.finishCreation(annotation, element);
      return;
    }

    try {
      if (isVolumeViewport) {
        const result = calculateNasalSeptumDeviationInWorld(points[0], points[1], points[2]);
        if (!validWorldPoint(result.projectionPoint)) {
          throw new Error('No se pudo calcular el punto de proyección');
        }
        points[3] = [...result.projectionPoint];
        (annotation.metadata as any).pixelSpacing = pixelSpacing;
        data.pixelSpacing = pixelSpacing;
        data.axisLengthMm = result.axisLengthMm;
        data.deviationLengthMm = result.deviationLengthMm;
        data.error = undefined;
        this.debug('cálculo MPR completado después del tercer click', {
          projectionWorld: result.projectionPoint,
          axisLengthMm: data.axisLengthMm,
          deviationLengthMm: data.deviationLengthMm,
        });
        this.finishCreation(annotation, element, true);
        return;
      }

      const axisStartIndex = imageData.worldToIndex(points[0]);
      const axisEndIndex = imageData.worldToIndex(points[1]);
      const deviationIndex = imageData.worldToIndex(points[2]);
      const result = calculateNasalSeptumDeviation(
        { x: axisStartIndex[0], y: axisStartIndex[1] },
        { x: axisEndIndex[0], y: axisEndIndex[1] },
        { x: deviationIndex[0], y: deviationIndex[1] },
        pixelSpacing
      );
      const projectionIndex = [result.projectionPoint.x, result.projectionPoint.y, deviationIndex[2] || 0];
      const projectionWorld = imageData.indexToWorld(projectionIndex);
      if (!validWorldPoint(projectionWorld)) {
        throw new Error('No se pudo calcular el punto de proyección');
      }

      points[3] = [...projectionWorld];
      (annotation.metadata as any).pixelSpacing = result.pixelSpacing;
      data.pixelSpacing = result.pixelSpacing;
      data.axisLengthMm = result.axisLengthMm;
      data.deviationLengthMm = result.deviationLengthMm;
      data.error = undefined;
      this.debug('cálculo completado después del tercer click', {
        axisStartIndex,
        axisEndIndex,
        deviationIndex,
        projectionIndex,
        projectionWorld,
        axisLengthMm: data.axisLengthMm,
        deviationLengthMm: data.deviationLengthMm,
        pixelSpacing: data.pixelSpacing,
      });
    } catch (error) {
      data.error = error instanceof Error ? error.message : 'No se pudo calcular la desviación';
      console.error('[NasalSeptumDeviationTool] error calculando proyección', error);
    }

    this.finishCreation(annotation, element, data.error === undefined);
  }

  private finishCreation(annotation: Annotation, element: HTMLDivElement, completed = false): void {
    const data = annotation.data.nasalSeptumDeviation as NasalSeptumToolData;
    data.step = completed && annotation.data.handles.points.length >= 4 ? 4 : 3;
    this.detachCreationListeners(element);
    this.creation = null;
    // Keep the interaction locked until the current normalized MOUSE_DOWN
    // finishes bubbling. Otherwise Cornerstone's MOUSE_DOWN_ACTIVATE handler
    // starts a second annotation from the same third click.
    window.setTimeout(() => {
      if (!this.creation) {
        cornerstoneTools.state.isInteractingWithTool = false;
      }
    }, 0);
    annotation.highlighted = false;
    annotation.invalidated = true;
    this.debug('finalizando anotación', {
      annotationUID: annotation.annotationUID,
      step: data.step,
      points: annotation.data.handles.points,
      error: data.error,
    });
    dispatchAnnotationEvent(cornerstoneTools.Enums.Events.ANNOTATION_COMPLETED, annotation, element);
    getEnabledElement(element).viewport.render();
  }

  private detachCreationListeners(element: HTMLDivElement): void {
    element.removeEventListener(
      cornerstoneTools.Enums.Events.MOUSE_DOWN,
      this.handleCreationMouseDown as EventListener
    );
  }

  private getPixelSpacing(imageId: string, imageData: any): number[] | undefined {
    const imagePlaneModule = imageId
      ? metaData.get('imagePlaneModule', imageId) as { pixelSpacing?: number[] } | undefined
      : undefined;
    const metadataSpacing = imagePlaneModule?.pixelSpacing;
    if (isValidPixelSpacing(metadataSpacing)) return metadataSpacing;

    const imageSpacing = imageData?.getSpacing?.() || imageData?.spacing;
    return isValidPixelSpacing(imageSpacing) ? imageSpacing : undefined;
  }

  private getVolumePixelSpacing(imageData: any): [number, number] | undefined {
    const spacing = imageData?.getSpacing?.() || imageData?.spacing;
    const values = Array.isArray(spacing)
      ? spacing
      : ArrayBuffer.isView(spacing)
        ? Array.from(spacing as unknown as ArrayLike<number>)
        : null;
    if (!values || values.length < 2) return undefined;

    // Volume spacing is ordered [x, y, z], while the persisted DICOM
    // PixelSpacing contract is [rowSpacing, columnSpacing].
    const pixelSpacing = [Number(values[1]), Number(values[0])];
    return isValidPixelSpacing(pixelSpacing)
      ? pixelSpacing as [number, number]
      : undefined;
  }

  private isVolumeViewport(viewport: any): boolean {
    const viewportType = viewport?.getType?.() || viewport?.type;
    return String(viewport?.id || '').startsWith('mpr-') ||
      viewportType === 'ORTHOGRAPHIC' || viewportType === 'VOLUME_3D' ||
      typeof viewport?.getCurrentImageId !== 'function';
  }

  filterInteractableAnnotationsForElement(
    element: HTMLDivElement,
    annotations: Annotation[]
  ): Annotation[] {
    const filtered = super.filterInteractableAnnotationsForElement(element, annotations);
    const currentImageId = getEnabledElement(element).viewport.getCurrentImageId?.();
    if (!currentImageId) return filtered;

    // Restored measurements can briefly carry a stale plane restriction even
    // though their referenced DICOM image is the current stack image. Keep an
    // exact image match visible and still hide it on every other slice.
    const exactImageAnnotations = annotations.filter(annotation =>
      annotation.metadata?.referencedImageId === currentImageId
    );
    return Array.from(new Map(
      [...filtered, ...exactImageAnnotations]
        .map(annotation => [annotation.annotationUID, annotation])
    ).values());
  }

  private recalculate(annotation: Annotation, viewport: any): void {
    const points = annotation.data.handles.points as CoreTypes.Point3[];
    const data = annotation.data.nasalSeptumDeviation as NasalSeptumToolData;
    if (points.length < 3 || !data.pixelSpacing) return;

    const imageData: any = viewport.getImageData()?.imageData || viewport.getImageData();
    if (!imageData?.worldToIndex || !imageData.indexToWorld) return;

    try {
      if (this.isVolumeViewport(viewport)) {
        const result = calculateNasalSeptumDeviationInWorld(points[0], points[1], points[2]);
        if (!validWorldPoint(result.projectionPoint)) return;
        points[3] = [...result.projectionPoint];
        data.axisLengthMm = result.axisLengthMm;
        data.deviationLengthMm = result.deviationLengthMm;
        data.error = undefined;
        annotation.invalidated = true;
        return;
      }

      const axisStart = imageData.worldToIndex(points[0]);
      const axisEnd = imageData.worldToIndex(points[1]);
      const deviation = imageData.worldToIndex(points[2]);
      const result = calculateNasalSeptumDeviation(
        { x: axisStart[0], y: axisStart[1] },
        { x: axisEnd[0], y: axisEnd[1] },
        { x: deviation[0], y: deviation[1] },
        data.pixelSpacing
      );
      const projectionWorld = imageData.indexToWorld([
        result.projectionPoint.x,
        result.projectionPoint.y,
        deviation[2] || 0,
      ]);
      if (!validWorldPoint(projectionWorld)) return;
      points[3] = [...projectionWorld];
      data.axisLengthMm = result.axisLengthMm;
      data.deviationLengthMm = result.deviationLengthMm;
      data.error = undefined;
      annotation.invalidated = true;
    } catch (error) {
      data.error = error instanceof Error ? error.message : 'No se pudo recalcular la desviación';
    }
  }

  isPointNearTool = (
    element: HTMLDivElement,
    annotation: Annotation,
    canvasCoords: CoreTypes.Point2,
    proximity: number
  ): boolean => {
    const { viewport } = getEnabledElement(element);
    const points = annotation.data.handles.points as CoreTypes.Point3[];
    if (points.length < 2) return false;

    const canvasPoints = points.map(point => viewport.worldToCanvas(point));
    if (pointDistanceToSegment(canvasCoords, canvasPoints[0], canvasPoints[1]) <= proximity) return true;
    if (canvasPoints.length >= 4 && pointDistanceToSegment(canvasCoords, canvasPoints[2], canvasPoints[3]) <= proximity) return true;
    return false;
  };

  toolSelectedCallback = (evt: InteractionEvent, annotation: Annotation): void => {
    const element = evt.detail.element as HTMLDivElement;
    annotation.highlighted = true;
    this.nasalEditData = { annotation, element };
    cornerstoneTools.state.isInteractingWithTool = true;
    this.attachEditListeners(element);
    evt.preventDefault();
    getEnabledElement(element).viewport.render();
  };

  handleSelectedCallback = (evt: InteractionEvent, annotation: Annotation, handle: ToolHandle): void => {
    const element = evt.detail.element as HTMLDivElement;
    const points = annotation.data.handles.points as CoreTypes.Point3[];
    const handleIndex = points.findIndex(point => point === handle);
    if (handleIndex === 3) {
      evt.preventDefault();
      return;
    }
    annotation.highlighted = true;
    this.nasalEditData = { annotation, element, handleIndex };
    cornerstoneTools.state.isInteractingWithTool = true;
    this.attachEditListeners(element);
    evt.preventDefault();
    getEnabledElement(element).viewport.render();
  };

  private attachEditListeners(element: HTMLDivElement): void {
    element.addEventListener(
      cornerstoneTools.Enums.Events.MOUSE_DRAG,
      this.handleEditDrag as EventListener
    );
    element.addEventListener(
      cornerstoneTools.Enums.Events.MOUSE_UP,
      this.handleEditEnd as EventListener
    );
    element.addEventListener(
      cornerstoneTools.Enums.Events.MOUSE_CLICK,
      this.handleEditEnd as EventListener
    );
  }

  private detachEditListeners(element: HTMLDivElement): void {
    element.removeEventListener(
      cornerstoneTools.Enums.Events.MOUSE_DRAG,
      this.handleEditDrag as EventListener
    );
    element.removeEventListener(
      cornerstoneTools.Enums.Events.MOUSE_UP,
      this.handleEditEnd as EventListener
    );
    element.removeEventListener(
      cornerstoneTools.Enums.Events.MOUSE_CLICK,
      this.handleEditEnd as EventListener
    );
  }

  private handleEditDrag = (rawEvent: Event): void => {
    const editData = this.nasalEditData;
    if (!editData) return;

    const evt = rawEvent as unknown as InteractionEvent;
    const currentWorld = evt.detail?.currentPoints?.world;
    if (!validWorldPoint(currentWorld)) return;

    const points = editData.annotation.data.handles.points as CoreTypes.Point3[];
    if (editData.handleIndex === undefined) {
      if (!editData.lastWorld) {
        editData.lastWorld = [...currentWorld];
        return;
      }
      const delta = currentWorld.map((value, index) => value - editData.lastWorld![index]) as CoreTypes.Point3;
      points.slice(0, 3).forEach(point => {
        point[0] += delta[0];
        point[1] += delta[1];
        point[2] += delta[2];
      });
      editData.lastWorld = [...currentWorld];
    } else {
      points[editData.handleIndex] = [...currentWorld];
    }

    const { viewport } = getEnabledElement(editData.element);
    this.recalculate(editData.annotation, viewport);
    dispatchAnnotationEvent(cornerstoneTools.Enums.Events.ANNOTATION_MODIFIED, editData.annotation, editData.element);
    viewport.render();
  };

  private handleEditEnd = (rawEvent: Event): void => {
    const editData = this.nasalEditData;
    if (!editData) return;

    const evt = rawEvent as unknown as InteractionEvent;
    const nativeEvent = evt.detail?.event as { preventDefault?: () => void } | undefined;
    nativeEvent?.preventDefault?.();
    this.detachEditListeners(editData.element);
    editData.annotation.data.handles.activeHandleIndex = null;
    editData.annotation.highlighted = false;
    this.nasalEditData = null;
    cornerstoneTools.state.isInteractingWithTool = false;
    dispatchAnnotationEvent(cornerstoneTools.Enums.Events.ANNOTATION_MODIFIED, editData.annotation, editData.element);
    getEnabledElement(editData.element).viewport.render();
  };

  cancel = (element: HTMLDivElement): string | undefined => {
    if (this.creation) {
      const annotationUID = this.creation.annotation.annotationUID;
      this.detachCreationListeners(this.creation.element);
      cornerstoneTools.annotation.state.removeAnnotation(annotationUID);
      this.creation = null;
      cornerstoneTools.state.isInteractingWithTool = false;
      getEnabledElement(element).viewport.render();
      return annotationUID;
    }
    if (this.nasalEditData) {
      this.detachEditListeners(this.nasalEditData.element);
      this.nasalEditData = null;
      cornerstoneTools.state.isInteractingWithTool = false;
      getEnabledElement(element).viewport.render();
    }
    return undefined;
  };

  renderAnnotation = (
    enabledElement: CoreTypes.IEnabledElement,
    svgDrawingHelper: SvgDrawingHelper
  ): boolean => {
    const { viewport } = enabledElement;
    const annotations = cornerstoneTools.annotation.state
      .getAllAnnotations()
      .filter(annotation => (annotation as any).toolName === this.getToolName() || annotation.metadata?.toolName === this.getToolName());
    const filteredAnnotations = this.filterInteractableAnnotationsForElement(
      viewport.element,
      annotations
    );
    const currentImageId = viewport.getCurrentImageId?.();
    // StackViewport's generic view-reference filter can reject a restored
    // custom annotation when the camera/view reference was rebuilt before the
    // target image finished loading. The annotation is still valid when its
    // referenced SOP image is the current stack image, so keep that exact-image
    // match as a safe fallback. This is intentionally narrower than marking it
    // as a canvas annotation, which would draw it on every slice.
    const exactImageAnnotations = currentImageId
      ? annotations.filter(annotation => annotation.metadata?.referencedImageId === currentImageId)
      : [];
    const annotationsForRender = Array.from(new Map(
      [...filteredAnnotations, ...exactImageAnnotations]
        .map(annotation => [annotation.annotationUID, annotation])
    ).values());
    let rendered = false;

    annotationsForRender.forEach(annotation => {
      const points = annotation.data.handles.points as CoreTypes.Point3[];
      const data = annotation.data.nasalSeptumDeviation as NasalSeptumToolData;
      const step = Math.min(data?.step || points.length, points.length);
      if (step < 1) return;

      const canvasPoints = points.slice(0, step).map(point => viewport.worldToCanvas(point));
      const renderSignature = JSON.stringify({
        step,
        points: points.slice(0, step),
        axisLengthMm: data?.axisLengthMm,
        deviationLengthMm: data?.deviationLengthMm,
        error: data?.error,
      });
      if (this.renderLogState.get(annotation.annotationUID) !== renderSignature) {
        this.renderLogState.set(annotation.annotationUID, renderSignature);
        this.debug('renderAnnotation', {
          annotationUID: annotation.annotationUID,
          step,
          pointCount: points.length,
          canvasPointCount: canvasPoints.length,
          hasAxis: canvasPoints.length >= 2,
          hasPerpendicular: canvasPoints.length >= 4,
          error: data?.error,
        });
      }
      const styleSpecifier = {
        toolGroupId: this.toolGroupId,
        toolName: this.getToolName(),
        viewportId: enabledElement.viewport.id,
        annotationUID: annotation.annotationUID,
      };
      const style = this.getAnnotationStyle({ annotation, styleSpecifier });
      const color = style.color || NASAL_SEPTUM_DEVIATION_COLOR;
      const lineWidth = style.lineWidth || 2;
      const lineDash = style.lineDash;

      if (canvasPoints.length >= 2) {
        cornerstoneTools.drawing.drawLine(
          svgDrawingHelper,
          annotation.annotationUID,
          'axis',
          canvasPoints[0],
          canvasPoints[1],
          { color, width: lineWidth, lineDash, shadow: style.shadow },
          `${annotation.annotationUID}-axis`
        );
      }
      if (canvasPoints.length >= 4) {
        cornerstoneTools.drawing.drawLine(
          svgDrawingHelper,
          annotation.annotationUID,
          'deviation',
          canvasPoints[2],
          canvasPoints[3],
          { color, width: lineWidth, lineDash: '4,2', shadow: style.shadow },
          `${annotation.annotationUID}-deviation`
        );
      }

      cornerstoneTools.drawing.drawHandles(
        svgDrawingHelper,
        annotation.annotationUID,
        'handles',
        canvasPoints,
        { color, lineDash, lineWidth }
      );

      if (data.axisLengthMm !== undefined && data.deviationLengthMm !== undefined && canvasPoints.length >= 4) {
        const textPosition: CoreTypes.Point2 = [
          (canvasPoints[0][0] + canvasPoints[1][0]) / 2 + 12,
          (canvasPoints[0][1] + canvasPoints[1][1]) / 2,
        ];
        cornerstoneTools.drawing.drawTextBox(
          svgDrawingHelper,
          annotation.annotationUID,
          'stats',
          [
            `Eje: ${data.axisLengthMm.toFixed(1)} mm`,
            `Desviación: ${data.deviationLengthMm.toFixed(1)} mm`,
          ],
          textPosition,
          { color, background: 'rgba(0, 0, 0, 0.65)', padding: 5 }
        );
      }
      rendered = true;
    });

    return rendered;
  };
}
